### ISSUE TITLE
Rendering Markdown as part of a view

### ISSUE THREAD

**Issue by StefanHagen** [afeld/html_pipeline_rails#5]
Hello Aiden! Your colleague James Dennes recommended your gem (html_pipeline_rails) to render markdown on my personal RoR website. After that I looked it up, and as I understand, you can use your gem to render complete views in Markdown using the Markdown .md extension. However I would like to know how I’d go about rendering part of a view in markdown. Warning, I am fairly new to Ror. Here’s what I’m trying to accomplish: I’m trying to build an admin system which can be used to post articles on my website. So for an article I have a form with a ‚title’ and ‚body’ field. I would like to format my text input in the ,body’ field in Markdown, and when the article is rendered on the website, it will look like the ‚Github Style’ Markdown. Is there a way to accomplish this using your gem?

**Comment by afeld** [comment]
You can accomplish this with something like the following:

``` erb
<%# app/views/articles/show.html.erb %>

<div class="article-contents">
  <%= render 'contents' %>
</div>
```

``` markdown
<!-- app/views/articles/_contents.md -->

## <%= @article.title %>

**by <%= @article.author %>**

<%= @article.body %>
```

There is a subtle distinction here between views that are written in Mardown (text saved in the `app/views/**/*.md` files), and Markdown that's injected into the template via ERB tags, a la the `@article.body` above.  Luckily, they both work via this gem.

I actually didn't realize that the ERB strings would be interpreted as Markdown until you asked the question, but added a test to confirm this in https://github.com/afeld/html_pipeline_rails/pull/6.  I also [attempted to clarify this](https://github.com/afeld/html_pipeline_rails/compare/ebfa39585c23394281283e94e60e83660f0f526a...bde7b21) in the README.

Let me know if that doesn't make sense!

/cc @jdennes

**Comment by StefanHagen** [comment]
Thanks very much! You've been a big help!
